version: "3.8"

services:
  app:
    image: platziapp
    environment:
      MONGO_URL: "mongodb://db:27017/test"
      # Agregamos las variables de entorno 
    depends_on:
      - db
    ports:
      - "3000:3000"

  db:
    image: mongo
