version: '3.8'

services:
  app:
    # image: platziapp
    build: .
    environment:
      MONGO_URL: 'mongodb://db:27017/test'
      # Agregamos las variables de entorno
    depends_on:
      - db
    volumes:
      - .:/usr/src
      - /usr/src/node_modules #se volvera read only

  db:
    image: mongo

  server:
    image: dockercloud/haproxy
    links:
      - app
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
