version: "3.8"

services:
  app:
    build: .
    # image: platziapp
    environment:
      MONGO_URL: "mongodb://db:27017/test"
    depends_on:
      - db
    ports:
      - "3000-3005:3000"
    volumes:
      - .:/usr/src
      - /usr/src/node_modules #ignorar ruta dentro container
    command: npx nodemon index.js      

  db:
    image: mongo
